# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets: 
        square400x300: # The name of the filter, can be later used in the twig template
            quality: 75 # Compression quality, this image will be 75% the quality
            filters: # These are the filters of the filter set, many filters can be applied
                downscale:
                    max: [400, 300]
                upscale:
                    min: [400, 300]
                thumbnail:
                    size: [400, 300]
                    mode: outbound
                